const Ziggy = {
    url: 'http://localhost',
    port: null,
    defaults: {},
    routes: {
        'sanctum.csrf-cookie': { uri: 'sanctum/csrf-cookie', methods: ['GET', 'HEAD'] },
        'livewire.update': { uri: 'livewire/update', methods: ['POST'] },
        'livewire.upload-file': { uri: 'livewire/upload-file', methods: ['POST'] },
        'livewire.preview-file': { uri: 'livewire/preview-file/{filename}', methods: ['GET', 'HEAD'], parameters: ['filename'] },
        'ignition.healthCheck': { uri: '_ignition/health-check', methods: ['GET', 'HEAD'] },
        'ignition.executeSolution': { uri: '_ignition/execute-solution', methods: ['POST'] },
        'ignition.updateConfig': { uri: '_ignition/update-config', methods: ['POST'] },
        dashboard: { uri: 'admin/dashboard', methods: ['GET', 'HEAD'] },
        'role.index': { uri: 'admin/role', methods: ['GET', 'HEAD'] },
        'role.create': { uri: 'admin/role/create', methods: ['GET', 'HEAD'] },
        'role.store': { uri: 'admin/role', methods: ['POST'] },
        'role.show': { uri: 'admin/role/{role}', methods: ['GET', 'HEAD'], parameters: ['role'], bindings: { role: 'id' } },
        'role.edit': { uri: 'admin/role/{role}/edit', methods: ['GET', 'HEAD'], parameters: ['role'], bindings: { role: 'id' } },
        'role.update': { uri: 'admin/role/{role}', methods: ['PUT', 'PATCH'], parameters: ['role'], bindings: { role: 'id' } },
        'role.destroy': { uri: 'admin/role/{role}', methods: ['DELETE'], parameters: ['role'], bindings: { role: 'id' } },
        'role.destroys': { uri: 'admin/roles', methods: ['DELETE'] },
        'permission.index': { uri: 'admin/permission', methods: ['GET', 'HEAD'] },
        'permission.create': { uri: 'admin/permission/create', methods: ['GET', 'HEAD'] },
        'permission.store': { uri: 'admin/permission', methods: ['POST'] },
        'permission.show': { uri: 'admin/permission/{permission}', methods: ['GET', 'HEAD'], parameters: ['permission'], bindings: { permission: 'id' } },
        'permission.edit': { uri: 'admin/permission/{permission}/edit', methods: ['GET', 'HEAD'], parameters: ['permission'], bindings: { permission: 'id' } },
        'permission.update': { uri: 'admin/permission/{permission}', methods: ['PUT', 'PATCH'], parameters: ['permission'], bindings: { permission: 'id' } },
        'permission.destroy': { uri: 'admin/permission/{permission}', methods: ['DELETE'], parameters: ['permission'], bindings: { permission: 'id' } },
        'permission.datatables': { uri: 'admin/permission/datatables', methods: ['POST'] },
        'permission.destroys': { uri: 'admin/users', methods: ['DELETE'] },
        'user.index': { uri: 'admin/user', methods: ['GET', 'HEAD'] },
        'user.create': { uri: 'admin/user/create', methods: ['GET', 'HEAD'] },
        'user.store': { uri: 'admin/user', methods: ['POST'] },
        'user.show': { uri: 'admin/user/{user}', methods: ['GET', 'HEAD'], parameters: ['user'], bindings: { user: 'id' } },
        'user.edit': { uri: 'admin/user/{user}/edit', methods: ['GET', 'HEAD'], parameters: ['user'], bindings: { user: 'id' } },
        'user.update': { uri: 'admin/user/{user}', methods: ['PUT', 'PATCH'], parameters: ['user'], bindings: { user: 'id' } },
        'user.destroy': { uri: 'admin/user/{user}', methods: ['DELETE'], parameters: ['user'], bindings: { user: 'id' } },
        'user.datatables': { uri: 'admin/user/datatables', methods: ['POST'] },
        'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
        'profile.update': { uri: 'profile', methods: ['PATCH'] },
        'profile.destroy': { uri: 'profile', methods: ['DELETE'] },
        register: { uri: 'register', methods: ['GET', 'HEAD'] },
        login: { uri: 'login', methods: ['GET', 'HEAD'] },
        'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
        'password.email': { uri: 'forgot-password', methods: ['POST'] },
        'password.reset': { uri: 'reset-password/{token}', methods: ['GET', 'HEAD'], parameters: ['token'] },
        'password.store': { uri: 'reset-password', methods: ['POST'] },
        'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
        'verification.verify': { uri: 'verify-email/{id}/{hash}', methods: ['GET', 'HEAD'], parameters: ['id', 'hash'] },
        'verification.send': { uri: 'email/verification-notification', methods: ['POST'] },
        'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
        'password.update': { uri: 'password', methods: ['PUT'] },
        logout: { uri: 'logout', methods: ['POST'] }
    }
};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}

export { Ziggy };
