/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        'sanctum.csrf-cookie': [];
        'ignition.healthCheck': [];
        'ignition.executeSolution': [];
        'ignition.updateConfig': [];
        dashboard: [];
        'role.index': [];
        'role.create': [];
        'role.store': [];
        'role.show': [
            {
                name: 'role';
                binding: 'id';
            }
        ];
        'role.edit': [
            {
                name: 'role';
                binding: 'id';
            }
        ];
        'role.update': [
            {
                name: 'role';
                binding: 'id';
            }
        ];
        'role.destroy': [
            {
                name: 'role';
                binding: 'id';
            }
        ];
        'role.destroys': [];
        'profile.edit': [];
        'profile.update': [];
        'profile.destroy': [];
        register: [];
        login: [];
        'password.request': [];
        'password.email': [];
        'password.reset': [
            {
                name: 'token';
            }
        ];
        'password.store': [];
        'verification.notice': [];
        'verification.verify': [
            {
                name: 'id';
            },
            {
                name: 'hash';
            }
        ];
        'verification.send': [];
        'password.confirm': [];
        'password.update': [];
        logout: [];
    }
}
export {};
