/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename"
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "dashboard": [],
    "role.index": [],
    "role.create": [],
    "role.store": [],
    "role.show": [
        {
            "name": "role",
            "binding": "id"
        }
    ],
    "role.edit": [
        {
            "name": "role",
            "binding": "id"
        }
    ],
    "role.update": [
        {
            "name": "role",
            "binding": "id"
        }
    ],
    "role.destroy": [
        {
            "name": "role",
            "binding": "id"
        }
    ],
    "role.destroys": [],
    "permission.index": [],
    "permission.create": [],
    "permission.store": [],
    "permission.show": [
        {
            "name": "permission",
            "binding": "id"
        }
    ],
    "permission.edit": [
        {
            "name": "permission",
            "binding": "id"
        }
    ],
    "permission.update": [
        {
            "name": "permission",
            "binding": "id"
        }
    ],
    "permission.destroy": [
        {
            "name": "permission",
            "binding": "id"
        }
    ],
    "permission.datatables": [],
    "permission.destroys": [],
    "user.index": [],
    "user.create": [],
    "user.store": [],
    "user.show": [
        {
            "name": "user",
            "binding": "id"
        }
    ],
    "user.edit": [
        {
            "name": "user",
            "binding": "id"
        }
    ],
    "user.update": [
        {
            "name": "user",
            "binding": "id"
        }
    ],
    "user.destroy": [
        {
            "name": "user",
            "binding": "id"
        }
    ],
    "user.datatables": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token"
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id"
        },
        {
            "name": "hash"
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": []
}
}
export {};
